### ISSUE TITLE
0.24 (previously 0.23)

### ISSUE THREAD

**Issue by epb-644** [ReactiveX/RxSwing#20]
Preparing to release 0.23. Here are the changes:
- [Pull 11](https://github.com/ReactiveX/RxSwing/pull/11) Added Observable support for Item Events
- [Pull 15](https://github.com/ReactiveX/RxSwing/pull/15) Added support for property change events
- [Pull 17](https://github.com/ReactiveX/RxSwing/pull/17) Removed SwingScheduler's invokeLater when called from EDT
- [Pull 18](https://github.com/ReactiveX/RxSwing/pull/18) Automatically subscribe/unsubscribe on the EDT
- [Pull 21](https://github.com/ReactiveX/RxSwing/pull/21) Adding unsubscribeOn EDT calls to all event sources
- [Pull 22](https://github.com/ReactiveX/RxSwing/pull/22) Added DocumentEvent support

**Comment by benjchristensen** [comment]
I released it, but accidentally released as 0.24 :-/

**Comment by epb-644** [comment]
No problem, thanks Ben.

**Comment by epb-644** [comment]
Edited this release to be version 0.24
