### ISSUE TITLE
0.25

### ISSUE THREAD

**Issue by epb-644** [ReactiveX/RxSwing#26]
Preparing to release 0.25. The changes are: 
- [Pull 23](https://github.com/ReactiveX/RxSwing/pull/23) Add WindowEventSource
- [Pull 24](https://github.com/ReactiveX/RxSwing/pull/24) Fixed SwingScheduler
- [Pull 25](https://github.com/ReactiveX/RxSwing/pull/25) List selection event support

**Comment by benjchristensen** [comment]
cc @abersnaze to help get the release out

**Comment by benjchristensen** [comment]
Since I am no longer at Netflix I can't access the old Cloudbees system for this release. @abersnaze can help with that. But we should migrate this project to use Travis for releases so @eddieburns55 can do releases without anyone else.

**Comment by abersnaze** [comment]
I've copied over the travis config to the 0.x branch and set up the environment variables to enable publishing. Making a github release should trigger travis to build a publish the jar now.

**Comment by epb-644** [comment]
The 0.25.0 release is up. Thanks @benjchristensen and @abersnaze for your help!
